const products = [
    { name: "Smoked Slovakian Bacon", origin: "Slovakia", price: 16, img: "https://www.masterbuilt.com/cdn/shop/articles/Slow_20Smoked_20Bacon.jpg?v=1705428187", desc: "Classic dry-cured and beech-smoked bacon.", longDesc: "Made from premium pork belly using our generations-old family recipe.", wine: "Full-bodied Slovak Frankovka or Austrian Zweigelt" },
    { name: "Traditional Sausage", origin: "Slovakia", price: 14, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD0VVpm69Fkq_A5ZH8s5G0g5nwdmUXtoBVXw&s", desc: "Coarse-ground smoked sausage with natural spices.", longDesc: "Rich flavor developed through slow cold-smoking process.", wine: "Spicy Tempranillo or young Rioja" },
    { name: "Smoked Ham", origin: "Slovakia", price: 12, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIgtd4FKSblDLk1E4fHDtIR4kOxQmolatM3g&s", desc: "Slow-smoked premium leg ham.", longDesc: "Cured and smoked for weeks to achieve deep, complex taste.", wine: "Light Pinot Noir or chilled Lambrusco" },
    { name: "Speck Alto Adige", origin: "Italy", price: 18, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqK1LPuY_fvnYIy-nr2wMI1XfZonF9hz6CZA&s", desc: "Lightly smoked Alpine ham.", longDesc: "Seasoned with juniper, bay leaves and spices, then gently smoked.", wine: "Trentino Pinot Grigio or Alto Adige Gewürztraminer" },
    { name: "Pancetta Affumicata", origin: "Italy", price: 16, img: "https://www.gustini.sk/media/iopt/catalog/product/cache/5cd2659c5c312525b4bd4af8818bc486/7/7/77154_1.webp", desc: "Rolled and smoked Italian pork belly.", longDesc: "Essential ingredient for authentic Italian carbonara.", wine: "Chianti Classico or crisp Vermentino" },
    { name: "Coppa di Parma", origin: "Italy", price: 22, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRwQuKb2_mmO8ySK_GSe7jOZqa5dyNaeIYyg&s", desc: "Dry-cured pork neck delicacy.", longDesc: "Delicate marbling with black pepper and garlic seasoning.", wine: "Barolo or aged Brunello di Montalcino" },
    { name: "Chorizo Ibérico", origin: "Spain", price: 19, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvKW9IMAze3534ZhyU8OusysITqz7zuTzDDg&s", desc: "Smoky paprika sausage from Iberian pork.", longDesc: "Bold, spicy and full of character.", wine: "Spanish Garnacha or Ribera del Duero" },
    { name: "Jamón Ibérico", origin: "Spain", price: 45, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1vheBVCVYhGSqbiOgat-sIEcsINutIjfYoQ&s", desc: "Acorn-fed Iberian cured ham.", longDesc: "World-renowned premium ham with intense nutty flavor.", wine: "Fine Sherry (Oloroso) or aged Rioja Reserva" },
    { name: "Salchichón", origin: "Spain", price: 17, img: "https://jamonesibericosmadrid.com/wp-content/uploads/2018/02/2-11-salchichon-castano-det2.jpg", desc: "Traditional Spanish cured salami.", longDesc: "Coarse texture with excellent black pepper seasoning.", wine: "Spanish Tempranillo or Priorat" },
    { name: "Smoked Trout", origin: "Slovakia", price: 16, img: "https://www.oklahomajoes.co.nz/Images/Recipes/Main/smoked-trout.jpg", desc: "Delicate cold-smoked river trout.", longDesc: "Mild, flaky texture with subtle beech smoke aroma.", wine: "Chablis or crisp Sauvignon Blanc" },
    { name: "Smoked Mackerel", origin: "Scotland", price: 14, img: "https://www.gtcaviar.com/cdn/shop/files/mackerel1.jpg?v=1703171364&width=1445", desc: "Rich hot-smoked Atlantic mackerel.", longDesc: "Bold, oily flavor perfect for pâté or salads.", wine: "Sancerre or unoaked Chardonnay" },
    { name: "Smoked Herring (Kippers)", origin: "UK", price: 13, img: "https://www.smokedsalmon.co.uk/cdn/shop/files/product-image_011b091c-b8a4-446c-8bd1-5dc523fe7714.jpg?v=1708620660", desc: "Traditional cold-smoked kippers.", longDesc: "Classic breakfast delicacy with robust smoky taste.", wine: "Dry Riesling or English sparkling wine" },
    { name: "Smoked Gouda", origin: "Netherlands", price: 19, img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2A3zjI5UC59YfX_3p7DCh8J6op4obXFIW5g&s", desc: "Mild Dutch smoked gouda.", longDesc: "Creamy with a gentle smoky finish.", wine: "Pinot Noir or medium-bodied Merlot" },
    { name: "Smoked Cheddar", origin: "UK", price: 18, img: "https://pearlvalleycheese.com/cdn/shop/products/pearl-valley-smoked-cheddar-cheese.jpg?v=1737212207", desc: "Aged sharp smoked cheddar.", longDesc: "Intense smoke and sharp tang.", wine: "Cabernet Sauvignon or aged Port" },
    { name: "Idiazábal", origin: "Spain", price: 24, img: "https://despananyc.com/cdn/shop/products/Idiazabal_5f57f718-857a-4773-8da8-aa4bdf0dc501.jpg?v=1596735313&width=480", desc: "Basque smoked sheep cheese.", longDesc: "Nutty, buttery with beechwood smoke.", wine: "Txakoli or light Basque cider" },
    { name: "Smoked Provolone", origin: "Italy", price: 17, img: "https://en.emiliafood.love/cdn/shop/products/Mildprovolonevalpadanadoppdoemiliafoodloveselectedwithloveinitaly_2_2048x.jpg?v=1696517373", desc: "Italian smoked provolone.", longDesc: "Mild and stretchy with light smoke.", wine: "Nebbiolo or Barbera d'Alba" }
];

const wines = [
    { name: "Frankovka Modrá", origin: "Slovakia", price: 28, img: "https://via.placeholder.com/600x400/8c4a2f/ffffff?text=Frankovka", desc: "Full-bodied red with dark fruit notes", longDesc: "Excellent with smoked bacon and ham.", type: "Red" },
    { name: "Rizling Rýnsky", origin: "Slovakia", price: 24, img: "https://via.placeholder.com/600x400/d4af88/1a110c?text=Rizling", desc: "Elegant white with floral aroma", longDesc: "Pairs beautifully with smoked fish.", type: "White" },
    { name: "Pinot Noir Reserve", origin: "Austria", price: 32, img: "https://via.placeholder.com/600x400/8c4a2f/ffffff?text=Pinot+Noir", desc: "Light red with earthy undertones", longDesc: "Ideal companion for smoked ham.", type: "Red" }
];
